name: Docs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: # required for GitHub Pages
  contents: read
  pages: write
  id-token: write

jobs:
  js:
    name: TypeDoc for modal-js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "22"

      - run: npm ci
        working-directory: ./modal-js

      - uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
      - run: uv tool install pre-commit==4.5.1

      - run: pre-commit run js-docs --all-files --hook-stage manual

      - name: Upload docs artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./modal-js/docs

  deploy:
    name: Deploy to GitHub Pages
    needs: js
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages # creates/updates the Pages env
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - id: deploy
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
