name: Docs

on:
  push:
    branches:
      - thomasjpfan/check-js-docs
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: # required for GitHub Pages
  contents: read
  pages: write
  id-token: write

jobs:
  js:
    name: TypeDoc for modal-js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "22"

      - run: npm ci
        working-directory: ./modal-js

      - run: npm run docs
        working-directory: ./modal-js

      - name: Upload docs artifact
        # if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v7
        with:
          name: js-docs
          path: ./modal-js/docs

  deploy-docs:
    name: Deploy to GitHub Pages
    needs: js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3  # v8
        with:
          name: js-docs
          path: docs

      - run: ls -R docs
